specialities = [
    "Select the Speciality","Acute Care", "Acute Care - Hospital", "Administrator Long Term Services", 
    "Aged Care 3A", "Aged Care 4A", "Aged Care 5A", "AIN", "AIN1", "AIN2", 
    "AIN3", "AIN4", "AIN5", "AIN6", "AIN COVID Surge", "Anti Partum", "ANUM", 
    "Assistant Chief Nursing Officer", "Burns Speciality Care Unit", "Cardiac", 
    "Cardiac Cath Lab", "Cardiology", "Cardiovascular Intensive Care Unit", 
    "Cardiovascular Operating Room", "Cardiovascular Surgery", "Case Management", 
    "Case Manager Nursing", "Certified Registered Nurse Anesthetist", "Circulator", 
    "Clinic/Dr. Office", "Clinics", "CMA - Clinic/Dr. Office", "CMA - LTC", 
    "CMA - MS", "CN1", "CN2", "CN3", "CN4", "CNA - Acute Care(hospital)", 
    "CNA - Clinic", "CNA - Emergency Room", "CNA - HomeHealth", 
    "CNA- Long Term Care / Rehab", "CNA - Sitter", "CNO Acute Care Services", 
    "Contact Tracer (Remote)", "Coronary Care Unity", "Corrections", "Counselor", 
    "Critical Care Medicine", "CRNA (Nurse Anesthetist)-OR", "CRNA - Spinal Block", 
    "CSTFA (Certified Surgical Tech First Assist)", "CT Scan technologist", 
    "CT Tech (Computed Tomography)", "CVOR Technologist", "Diabetes Specialist", 
    "Director(Clinical)", "Dir Laboratory Services", "Disregard", "Doctors Office", 
    "DON Acute Care Services", "DON Case Management", "DON Infection Prevention", 
    "DON Long Term Care Services", "DON Med Surg", "DON Surgical Services", 
    "DON Womens & Childrens", "Echo Tech", "EEN 2.1", "EEN 2.2", "EEN 2.3", 
    "EEN 2.4", "EEN 2.5", "EEN 2.6", "EEN 2.7", "EEN COVID Surge", "Elementary", 
    "Emergency", "Emergency Medicine", "Emergency Room", "Emergency Room - OBS", 
    "Endoscopy", "Family Medicine", "First Assist Operating Room", "Geriatrics", 
    "GI Lab", "Health Educator", "Hematology", "Hemodialysis", "Home Health", 
    "Homeschool", "Hospice", "Hospital", "Hospitalist", "House Supervisor RN", 
    "Human Resources", "Infection Prevention", "Infection Preventionist", 
    "Inpatient", "Instrument Tech 3", "Instrument Tech 4", "Intensive Care Unit", 
    "Internal Medicine", "Interventional Radiology", "Labor and Delivery", "Lab Tech", 
    "Lab Tech Phelbotomist", "Long-Term Care Facility (Nursing Home)", 
    "Long Term Care - Nursing Home", "Long Term Care- Nursing Home", 
    "Long Term Care - Rehab", "LPN - Acute Care", "LPN- Clinic Doctors Office", 
    "LPN - Corrections", "LPN - Geriatrics", "LPN - LTC Nursing Home", 
    "LPN - Medical Surgical", "LPN - TELE", "LPN - Trauma ICU", "MA - Clinic/Dr. Office", 
    "Mammographer", "Manager Case Management (SWorker)", "Manager Laboratory Services", 
    "Manager Med Staff Services", "Manager RN Cath lab", "Manager RN OR", 
    "Manager Sterile Processing", "Medical/Surgical", "Medical Intensive Care Unit", 
    "Medical Surgical Telemetry", "Medical Technologist", "Medical Technologist - MT", 
    "Middle School", "Mother and Baby Unit", "MRI Tech", "Neonatal, Critical Care-Intensivist", 
    "Neonatal Intensive Care - Level 1", "Neonatal Intensive Care - Level 2", 
    "Neonatal Intensive Care - Level 3", "Neurology", "Neuro-Surgery", 
    "Neurosurgical Intensive Care Unit", "Not Retrieved from BlueSky", 
    "NP Clinic Dr. Office", "NP Critical Care ICU", "NP Pediatric", "NP Psych (Behavioral Health)", 
    "NUM", "Nurse Paralegal", "OB/GYN", "Obstetrics & Gynecology", "Occupational Health", 
    "Occupational Therapist", "Oncology", "Operating Room", "Orthopedics", "Outpatient", 
    "Outpatient Clinics", "PCA 3", "PCA 4", "PCA COVID Surge", "Pediatric Emergency Room", 
    "Pediatric Psychiatry", "Pediatrics", "Pediatrics Cardiac ICU", "Pediatrics Intensive Care", 
    "Pediatrics Oncology", "Pediatrics Operating Room", "Pharmacist - Outpatient", 
    "Pharm Tech - Inpatient", "Physical Therapist", "Physician Assistant", 
    "Post Anesthetic Care Unit", "Post Critical Care Unit - Stepdown", "Post Partum", 
    "Pre - Op", "Preschool", "Primary Care", "Professor", "PSA", "Psych/Mental Health", 
    "Psychiatric/Behavioral Health", "Quality", "RAD Tech (Xray Tech) 4 plus year degree", 
    "Rehabilitation", "Respirarory Therapist", "Respiratory", "Respiratory Technician", 
    "Retail", "RN-Cardiac Cath Lab", "RN-Case Manager", "RN-CCU - Coronary Care", 
    "RN-Charge Nurse", "RN-CISD (Coronary ICU stepdown) DO NOT USE", "RN-Clinic/Dr. Office", 
    "RN-Clinical Nurse Manager", "RN COVID Surge", "RN-CVICU - Cardiovascular Care", 
    "RN-CVPICU - Peds Cardiac ICU", "RN-Dialysis (Hemodialysis)", "RN-Dialysis (Peritoneal)", 
    "RN-Endoscopy/GI Lab", "RN-ER - Emergency Medicine", "RN-Geriatrics (Nursing Home DO NOT USE)", 
    "RN-Home Health", "RN-Hospice", "RN-ICU - Intensive Care Unit", "RN-Interventional Radiology", 
    "RN-Labor and Delivery", "RN-LTAC", "RN-LTC Nursing Home Long-Term Care", 
    "RN- Medical Surgical Telemetry", "RN-MedSurg MS", "RN-MICU - Medical Intensive Care", 
    "RN-MISD (Medical ICU stepdown) DO NOT USE", "RN-Mother and Baby", 
    "RN-Neuro ICU - Neurosurgical Intensive Care", "RN-Neurology/Stroke", "RN-NICU 3 - Neonatal Intensive Care", 
    "RN-OB/GYN", "RN-Oncology", "RN-OR - Operating Room", "RN-Orthopedics", "RN-Other (DO NO USE)", 
    "RN-PACU - Post Anesthetic Care", "RN-PCU/IMC (Post Critical Care Unit) Stepdown", 
    "RN-PCU Progressive Care Unit DO NOT USE", "RN-Pediatrics", "RN-PICC/IV Infusion", 
    "RN-PICU - Pediatrics Intensive Care", "RN-Psychiatric/Behavioral Health", 
    "RN-Rehabilitation", "RN-RM 2.1", "RN-RM 2.10", "RN-RM 2.10 Grad Certification", 
    "RN-RM 2.10 In Charge", "RN-RM 2.10 Masters/Doctorate", "RN-RM 2.10 Post Grad Diploma", 
    "RN-RM 2.1 Grad Certification", "RN-RM 2.1 In Charge", "RN-RM 2.1 Masters/Doctorate", 
    "RN-RM 2.1 Post Grad Diploma", "RN-RM 2.2", "RN-RM 2.2 Grad Certification", 
    "RN-RM 2.2 In Charge", "RN-RM 2.2 Masters/Doctorate", "RN-RM 2.2 Post Grad Diploma", 
    "RN-RM 2.3", "RN-RM 2.3 Grad Certification", "RN-RM 2.3 In Charge", "RN-RM 2.3 Masters/Doctorate", 
    "RN-RM 2.3 Post Grad Diploma", "RN-RM 2.4", "RN-RM 2.4 Grad Certification", 
    "RN-RM 2.4 In Charge", "RN-RM 2.4 Masters/Doctorate", "RN-RM 2.4 Post Grad Diploma", 
    "RN-RM 2.5", "RN-RM 2.5 Grad Certification", "RN-RM 2.5 In Charge", "RN-RM 2.5 Masters/Doctorate", 
    "RN-RM 2.5 Post Grad Diploma", "RN-RM 2.6", "RN-RM 2.6 Grad Certification", 
    "RN-RM 2.6 In Charge", "RN-RM 2.6 Masters/Doctorate", "RN-RM 2.6 Post Grad Diploma", 
    "RN-RM 2.7", "RN-RM 2.7 Grad Certification", "RN-RM 2.7 In Charge", 
    "RN-RM 2.7 Masters/Doctorate", "RN-RM 2.7 Post Grad Diploma", "RN-RM 2.8", 
    "RN-RM 2.8 Grad Certification", "RN-RM 2.8 In Charge", "RN-RM 2.8 Masters/Doctorate", 
    "RN-RM 2.8 Post Grad Diploma", "RN-RM 2.9", "RN-RM 2.9 Grad Certification", 
    "RN-RM 2.9 In Charge", "RN-RM 2.9 Masters/Doctorate", "RN-RM 2.9 Post Grad Diploma", 
    "RN-RM 3.0", "RN-RM 3.0 Grad Certification", "RN-RM 3.0 In Charge", "RN-RM 3.0 Masters/Doctorate", 
    "RN-RM 3.0 Post Grad Diploma"
]

category_subcategories = [
    ["Clinical", [
        "Acute Care General",
        "Case Management",
        "Critical Care",
        "Emergency Room",
        "Home Health",
        "Mental Health",
        "Neonatal",
        "Nursing Home and Rehab Hospitals",
        "Operating Room",
        "Outpatient Clinics",
        "Paralegal",
        "Pediatrics",
        "Women's Services"
    ]],
    ["Non Clinical", []],
    ["Education", ["Education"]],
    ["Management", []],
    ["Allied Health", []],
    ["Administration", []],
    ["Pharmacy",[]],
    ["Social Work", ["Social Work"]],
    ["Locums", ["Locums"]]
]

categories_discipline = [
    ["Clinical", [
        "Aged Care",
        "Certified Clinical Medical Assistant",
        "Certified Medical Assistant",
        "Certified Nursing Assistant",
        "Charge Nurse",
        "Clinical Facilitator",
        "EEN",
        "EN",
        "LPN/RPN",
        "LPN RPN Fresher (New Grad)",
        "PSW/CCA/RCA",
        "Registered Nurse",
        "RN",
        "RN Fresher"
    ]],
    ["Non Clinical", [
        "Information Security Analyst",
        "Instrument Tech",
        "Theatre Tech"
    ]],
    ["Education", [
        "Educator",
        "Principal"
    ]],
    ["Management", [
        "Assistant Vice President",
        "Case Manager",
        "CEO",
        "CFO",
        "Chief Nursing Executive",
        "Chief Nursing Officer",
        "Clinical Nurse Manager",
        "Director(Clinical)",
        "Director (Non-Clinical)",
        "House Supervisor",
        "Manager(Clinical)",
        "Manager( Non clinical)",
        "President",
        "Supervisor",
        "Vice President"
    ]],
    ["Administration", [
        "Administrative Assistant",
        "Contact Tracer (Remote)",
        "Coordinator",
        "Unit Clerk"
    ]],
    ["Pharmacy", [
        "Pharmacist",
        "Pharmacy Technician"
    ]],
    ["Social Work", [
        "Licensed Clinical Social Worker"
    ]],
    ["Locums", [
        "Abdominal Radiology",
        "Addiction Medicine",
        "Addiction Psychiatry",
        "Adolescent Medicine",
        "Adult Cardiothoracic Anesthesiology",
        "Adult Congenital Heart Disease",
        "Adult Reconstructive Orthopaedics",
        "Advanced Heart Failure and Transplant Cardiology",
        "Aerospace Medicine",
        "Allergy and Immunology",
        "Anesthesiology",
        "Blood Banking/Transfusion Medicine",
        "Brain Injury Medicine",
        "Cardiovascular Disease",
        "Certified Registered Nurse Anesthetist",
        "Chemical Pathology",
        "Child Abuse Pediatrics",
        "Child and Adolescent Psychiatry",
        "Child Neurology",
        "Clinical Biochemical Genetics",
        "Clinical Cardiac Electrophysiology",
        "Clinical Informatics",
        "Clinical Neurophysiology",
        "Colon and Rectal Surgery",
        "Complex Family Planning",
        "Complex General Surgical Oncology",
        "Congenital Cardiac Surgery",
        "Consultation-Liaison Psychiatry",
        "Craniofacial Surgery",
        "Critical Care Medicine",
        "Cytopathology",
        "Dermatology",
        "Dermatopathology",
        "Developmental-Behavioral Pediatrics",
        "Diagnostic Radiology/Nuclear Medicine",
        "Emergency Medical Services",
        "Emergency Medicine",
        "Emergency Medicine/Anesthesiology",
        "Emergency Medicine/Family Medicine",
        "Endocrinology, Diabetes, and Metabolism",
        "Epilepsy",
        "Family Medicine",
        "Family Medicine/Osteopathic Neuromusculoskeletal Medicine",
        "Family Medicine/Preventive Medicine",
        "Foot and Ankle Orthopaedics",
        "Forensic Pathology",
        "Forensic Psychiatry",
        "Gastroenterology",
        "Geriatric Medicine",
        "Geriatric Psychiatry",
        "Gynecologic Oncology",
        "Hand Surgery",
        "Health Care Administration, Leadership, and Management",
        "Hematology",
        "Hematology and Medical Oncology",
        "Hematopathology",
        "Hospice and Palliative Medicine",
        "Infectious Disease",
        "Internal Medicine",
        "Internal Medicine/Anesthesiology",
        "Internal Medicine/Dermatology",
        "Internal Medicine/Emergency Medicine",
        "Internal Medicine/Emergency Medicine/Critical Care Medicine",
        "Internal Medicine/Family Medicine",
        "Internal Medicine/Medical Genetics and Genomics",
        "Internal Medicine/Pediatrics",
        "Internal Medicine/Physical Medicine and Rehabilitation",
        "Internal Medicine/Preventive Medicine",
        "Internal Medicine/Psychiatry",
        "Interventional Cardiology",
        "Interventional Pulmonology",
        "Interventional Radiology-Independent",
        "Interventional Radiology-Integrated",
        "Laboratory Genetics and Genomics",
        "Maternal-Fetal Medicine",
        "Medical Biochemical Genetics",
        "Medical Genetics and Genomics",
        "Medical Genetics and Genomics/Maternal-Fetal Medicine",
        "Medical Microbiology",
        "Medical Oncology",
        "Medical Toxicology",
        "Micrographic Surgery and Dermatologic Oncology",
        "Molecular Genetic Pathology",
        "Musculoskeletal Oncology",
        "Musculoskeletal Radiology",
        "Neonatal-Perinatal Medicine",
        "Nephrology",
        "Neurocritical Care",
        "Neurodevelopmental Disabilities",
        "Neuroendovascular Intervention",
        "Neurological Surgery",
        "Neurology",
        "Neurology/Physical Medicine and Rehabilitation",
        "Neuromuscular Medicine",
        "Neuropathology",
        "Neuroradiology",
        "Neurotology",
        "Nuclear Medicine",
        "Nuclear Radiology",
        "Nurse Practitioner",
        "Obstetric Anesthesiology",
        "Obstetrics and Gynecology",
        "Occupational and Environmental Medicine",
        "Ophthalmic Plastic and Reconstructive Surgery",
        "Ophthalmology",
        "Orthopaedic Sports Medicine",
        "Orthopaedic Surgery",
        "Orthopaedic Surgery of the Spine",
        "Orthopaedic Trauma",
        "Osteopathic Neuromusculoskeletal Medicine",
        "Otolaryngology-Head and Neck Surgery",
        "Pain Medicine",
        "Pathology-Anatomic and Clinical",
        "Pediatric Anesthesiology",
        "Pediatric Cardiac Anesthesiology",
        "Pediatric Cardiology",
        "Pediatric Critical Care Medicine",
        "Pediatric Dermatology",
        "Pediatric Emergency Medicine",
        "Pediatric Endocrinology",
        "Pediatric Gastroenterology",
        "Pediatric Hematology/Oncology",
        "Pediatric Hospital Medicine",
        "Pediatric Infectious Diseases",
        "Pediatric Nephrology",
        "Pediatric Orthopaedics",
        "Pediatric Otolaryngology",
        "Pediatric Pathology",
        "Pediatric Pulmonology",
        "Pediatric Radiology",
        "Pediatric Rehabilitation Medicine",
        "Pediatric Rheumatology",
        "Pediatric Surgery",
        "Pediatric Transplant Hepatology",
        "Pediatric Urology",
        "Pediatrics",
        "Pediatrics/Anesthesiology",
        "Pediatrics/Emergency Medicine",
        "Pediatrics/Medical Genetics and Genomics",
        "Pediatrics/Physical Medicine and Rehabilitation",
        "Pediatrics/Psychiatry/Child and Adolescent Psychiatry",
        "Physical Medicine and Rehabilitation",
        "Physician",
        "Physician Assistant",
        "Plastic Surgery",
        "Plastic Surgery-Integrated",
        "Psychiatry",
        "Psychiatry/Family Medicine",
        "Psychiatry/Neurology",
        "Public Health and General Preventive Medicine",
        "Pulmonary Disease",
        "Pulmonary Disease and Critical Care Medicine",
        "Radiation Oncology",
        "Radiology-Diagnostic",
        "Regional Anesthesiology and Acute Pain Medicine",
        "Reproductive Endocrinology and Infertility",
        "Reproductive Endocrinology and Infertility/Medical Genetics and Genomics",
        "Rheumatology",
        "Selective Pathology",
        "Sleep Medicine",
        "Spinal Cord Injury Medicine",
        "Sports Medicine",
        "Surgery-General",
        "Surgical Critical Care",
        "Thoracic Surgery",
        "Thoracic Surgery-Integrated",
        "Transitional Year",
        "Transplant Hepatology",
        "Undersea and Hyperbaric Medicine",
        "Urogynecology and Reconstructive Pelvic Surgery",
        "Urogynecology and Reconstructive Surgery",
        "Urology",
        "Vascular Neurology",
        "Vascular Surgery",
        "Vascular Surgery-Integrated"
    ]],
    ["Allied Health", [
        "Athletic Trainer",
        "Audiologist",
        "Cardiovascular Surgical Technician",
        "Cath Lab Technologist",
        "Certified Clinical Medical Assistant",
        "Certified Medical Assistant",
        "Certified Sterile Processing Technician",
        "Clinical Medical Admin Assistant",
        "CT Scan technologist",
        "CVOR Technologist",
        "Cytotechnologists",
        "Dental hygienists",
        "Diagnostic medical sonographers",
        "Dialysis Technician",
        "Dietician",
        "Echocardiographer",
        "Echo Tech",
        "EEG Technologist",
        "Emergency Medical Technician",
        "Endoscopy Technician",
        "Health Information Technician",
        "Interventional Radiology Technologist",
        "Lab Tech",
        "Lactation consultants",
        "Mammographer",
        "Medical Assistant",
        "Medical Licensed Technician",
        "Medical Technologist",
        "Mental Health Technician",
        "Midwife",
        "Monitor Technician",
        "MRI Technician",
        "Nuclear Medicine Technician",
        "Occupational Therapist",
        "Paramedic",
        "PCA",
        "Phlebotomist Technician",
        "Physical Therapist",
        "Physical Therapy Assistant",
        "Physicist",
        "Physiotherapist",
        "RAD Tech",
        "Respiratory Technician",
        "Respiratory Therapist",
        "Speech-Language Therapist",
        "Sterile Processing Technician",
        "Surgical Technician",
        "Surgical Technologist",
        "Telemetry Technician",
        "Ultrasonographer",
        "Vascular Technologist",
        "X-Ray Technician"
    ]]
]
