# Generated by Django 4.2.18 on 2025-02-03 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('facility_name', models.CharField(max_length=255)),
                ('bill_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_description', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_url', models.URLField(blank=True, null=True)),
                ('recruiter', models.CharField(blank=True, max_length=255, null=True)),
                ('recruiter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hot_job', models.BooleanField(default=False)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('positions', models.PositiveIntegerField(blank=True, null=True)),
                ('employer', models.CharField(blank=True, max_length=255, null=True)),
                ('discipline', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('shift', models.CharField(blank=True, max_length=100, null=True)),
                ('job_robotix_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vms_job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('publish', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
