# Generated by Django 4.2.18 on 2025-02-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_title_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
